# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
# Note: this package is intentionally named std to make sure the names of
# standard library symbols are preserved
name = "std"
version = "0.37.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
kani = {path="../kani"}

[features]
concrete_playback = ["kani/concrete_playback"]
