# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
[book]
title = "Kani RFC Book"
description = "Design documents for Kani Rust Verifier"
authors = ["Kani Developers"]
language = "en"
src = "src"

[output.html]
site-url = "/kani/rfc/"
git-repository-url = "https://github.com/model-checking/kani"
edit-url-template = "https://github.com/model-checking/kani/edit/main/rfc/{path}"
no-section-label = true

[output.html.playground]
runnable = false
