language: rust
sudo: false
dist: trusty
rust:
- 1.32.0
- stable
- beta
- nightly

# Install travis-cargo which sets `--feature unstable` for nightly builds automatically
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      (cd proptest && travis-cargo build) &&
      (cd proptest && travis-cargo test) &&
      (cd proptest && travis-cargo --only stable build -- --no-default-features --features fork) &&
      (cd proptest && travis-cargo --only stable build -- --lib --no-default-features --features std) &&
      (cd proptest && travis-cargo --only nightly build -- --no-default-features --features "alloc unstable") &&
      (cd proptest/test-persistence-location && ./run-tests.sh) &&
      cargo clean &&
      (cd proptest-derive && env TRAVIS_CARGO_NIGHTLY_FEATURE= travis-cargo build) &&
      (cd proptest-derive && env TRAVIS_CARGO_NIGHTLY_FEATURE= travis-cargo --only nightly test)

cache: cargo
