# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "kani_macros"
version = "0.57.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-error2 = { version = "2.0.0", features = ["nightly"] }
quote = "1.0.20"
syn = { version = "2.0.18", features = ["full", "visit-mut", "visit", "extra-traits"] }

[package.metadata.rust-analyzer]
# This package uses rustc crates.
rustc_private = true

[features]
no_core = []

[lints]
workspace = true
