# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
[package]
name = "arbitrary-variables"
version = "0.1.0"
edition = "2018"

[dependencies]
vector-map = "1.0.1"

[workspace]

[workspace.metadata.kani]
flags = { default-checks = false , unwind = "2" }
