# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
[package]
name = "kinds-of-failure"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "1.0.0"

[workspace]
