# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Kani CI
on: pull_request

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kani
        uses: actions/checkout@v2

      - name: Get paths for files added
        id: git-diff
        run: |
          ignore='(.clang-format|.diff|.md|.props|expected|ignore|gitignore|Cargo.lock)$'
          files=$(git diff --ignore-submodules=all --name-only --diff-filter=A ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v -E $ignore | xargs)
          echo "::set-output name=paths::$files"

      - name: Execute copyright check
        if: ${{ steps.git-diff.outputs.paths }}
        run: ./scripts/ci/copyright_check.py ${{ steps.git-diff.outputs.paths }}

      - name: Check C code formatting
        run: ./scripts/run-clang-format.sh -d

      - name: Check Python code formatting
        run: |
            pip3 install --upgrade autopep8
            ./scripts/run-autopep8.sh
